jenkins:
            
            service:
              type: LoadBalancer
            
            # Optional: Expose slave agent connections if your terraform pod needs external access
            slaveService:
              type: ClusterIP
            namespace: jenkins
